// Sample recipe data
const SAMPLE_RECIPES = [
  {
    id: 1,
    title: "Pasta Carbonara Premium",
    image:
      "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "TERPOPULER",
    time: 25,
    servings: 4,
    calories: 520,
    difficulty: "medium",
    rating: 4.8,
    reviews: 156,
    tags: ["vegetarian", "comfort-food"],
    category: "dinner",
    ingredients: [
      { name: "spaghetti", amount: 400, unit: "g", category: "pasta" },
      { name: "daging asap (pancetta)", amount: 200, unit: "g", category: "meat" },
      { name: "telur", amount: 4, unit: "butir", category: "dairy" },
      { name: "keju pecorino", amount: 100, unit: "g", category: "dairy" },
      { name: "keju parmesan", amount: 50, unit: "g", category: "dairy" },
      { name: "bawang putih", amount: 2, unit: "siung", category: "vegetables" },
      { name: "garam dan lada hitam", amount: 1, unit: "secukupnya", category: "spices" },
    ],
    steps: [
      {
        step: 1,
        instruction:
          "Rebus spaghetti dalam air mendidih yang diberi garam hingga al dente (sekitar 8-10 menit). Sementara itu, potong dadu pancetta dan cincang bawang putih.",
        time: 10,
        temperature: null,
        tips: "Pastikan air benar-benar mendidih sebelum memasukkan pasta",
      },
      {
        step: 2,
        instruction:
          "Panaskan wajan, tambahkan pancetta dan masak hingga garing. Tambahkan bawang putih cincang dan masak selama 1 menit hingga harum.",
        time: 5,
        temperature: "Medium-high",
        tips: "Jangan sampai bawang putih gosong",
      },
      {
        step: 3,
        instruction:
          "Dalam mangkuk, kocok telur, keju pecorino, keju parmesan, garam, dan lada hitam hingga tercampur rata.",
        time: 2,
        temperature: null,
        tips: "Gunakan keju yang sudah diparut halus",
      },
      {
        step: 4,
        instruction:
          "Tiriskan spaghetti, sisakan sedikit air rebusan. Segera campur spaghetti dengan campuran telur dan keju. Aduk cepat hingga saus mengental.",
        time: 2,
        temperature: null,
        tips: "Kunci sukses: aduk cepat agar telur tidak menggumpal",
      },
      {
        step: 5,
        instruction:
          "Tambahkan pancetta dan bawang putih ke spaghetti. Aduk rata. Sajikan segera dengan taburan keju parmesan dan lada hitam segar.",
        time: 1,
        temperature: null,
        tips: "Sajikan dalam piring yang sudah dihangatkan",
      },
    ],
    nutrition: {
      carbs: 45,
      protein: 25,
      fat: 20,
      fiber: 7,
      sugar: 3,
    },
    cost: 45000,
    prepTime: 15,
    cookTime: 25,
  },
  {
    id: 2,
    title: "Salad Quinoa Mediterania",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "SEHAT",
    time: 20,
    servings: 2,
    calories: 320,
    difficulty: "easy",
    rating: 4.6,
    reviews: 89,
    tags: ["vegan", "gluten-free", "healthy"],
    category: "lunch",
    ingredients: [
      { name: "quinoa", amount: 200, unit: "g", category: "grains" },
      { name: "mentimun", amount: 1, unit: "buah", category: "vegetables" },
      { name: "tomat ceri", amount: 200, unit: "g", category: "vegetables" },
      { name: "zaitun", amount: 100, unit: "g", category: "pantry" },
      { name: "daun mint", amount: 50, unit: "g", category: "herbs" },
      { name: "lemon", amount: 1, unit: "buah", category: "fruits" },
      { name: "minyak zaitun", amount: 3, unit: "sdm", category: "pantry" },
    ],
    steps: [
      {
        step: 1,
        instruction: "Cuci quinoa hingga bersih, lalu rebus dalam air mendidih selama 15 menit hingga empuk.",
        time: 15,
        temperature: null,
        tips: "Bilas quinoa sampai air bilasan jernih",
      },
      {
        step: 2,
        instruction: "Potong dadu mentimun dan tomat ceri. Cincang halus daun mint.",
        time: 5,
        temperature: null,
        tips: "Potong sayuran dengan ukuran yang seragam",
      },
      {
        step: 3,
        instruction: "Campur quinoa yang sudah dingin dengan sayuran, zaitun, dan mint.",
        time: 2,
        temperature: null,
        tips: "Pastikan quinoa sudah benar-benar dingin",
      },
      {
        step: 4,
        instruction: "Buat dressing dari perasan lemon dan minyak zaitun. Tuang ke salad dan aduk rata.",
        time: 3,
        temperature: null,
        tips: "Tambahkan garam dan lada sesuai selera",
      },
    ],
    nutrition: {
      carbs: 35,
      protein: 15,
      fat: 25,
      fiber: 15,
      sugar: 10,
    },
    cost: 25000,
    prepTime: 10,
    cookTime: 15,
  },
  {
    id: 3,
    title: "Nasi Goreng Spesial",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "FAVORIT",
    time: 30,
    servings: 3,
    calories: 450,
    difficulty: "medium",
    rating: 4.7,
    reviews: 203,
    tags: ["comfort-food", "indonesian"],
    category: "dinner",
    ingredients: [
      { name: "nasi putih", amount: 3, unit: "piring", category: "grains" },
      { name: "telur", amount: 2, unit: "butir", category: "dairy" },
      { name: "ayam fillet", amount: 200, unit: "g", category: "meat" },
      { name: "udang", amount: 150, unit: "g", category: "seafood" },
      { name: "bawang merah", amount: 5, unit: "siung", category: "vegetables" },
      { name: "bawang putih", amount: 3, unit: "siung", category: "vegetables" },
      { name: "cabai merah", amount: 3, unit: "buah", category: "vegetables" },
      { name: "kecap manis", amount: 3, unit: "sdm", category: "pantry" },
      { name: "garam", amount: 1, unit: "sdt", category: "spices" },
    ],
    steps: [
      {
        step: 1,
        instruction: "Potong ayam dan udang, lalu marinasi dengan garam dan lada selama 15 menit.",
        time: 15,
        temperature: null,
        tips: "Marinasi akan membuat daging lebih empuk",
      },
      {
        step: 2,
        instruction: "Haluskan bawang merah, bawang putih, dan cabai merah.",
        time: 5,
        temperature: null,
        tips: "Gunakan blender atau ulek hingga halus",
      },
      {
        step: 3,
        instruction: "Panaskan minyak, tumis bumbu halus hingga harum. Masukkan ayam dan udang, masak hingga matang.",
        time: 8,
        temperature: "Medium-high",
        tips: "Masak hingga ayam berubah warna",
      },
      {
        step: 4,
        instruction: "Kocok telur, buat orak-arik di wajan yang sama. Masukkan nasi, aduk rata.",
        time: 5,
        temperature: "Medium",
        tips: "Pastikan nasi tidak menggumpal",
      },
      {
        step: 5,
        instruction: "Tambahkan kecap manis, garam, dan lada. Aduk rata dan masak 2 menit. Sajikan panas.",
        time: 2,
        temperature: "Medium",
        tips: "Cicipi dan sesuaikan rasa",
      },
    ],
    nutrition: {
      carbs: 50,
      protein: 30,
      fat: 15,
      fiber: 5,
      sugar: 8,
    },
    cost: 35000,
    prepTime: 20,
    cookTime: 20,
  },
  {
    id: 4,
    title: "Smoothie Bowl Tropical",
    image:
      "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "SEHAT",
    time: 10,
    servings: 1,
    calories: 280,
    difficulty: "easy",
    rating: 4.5,
    reviews: 67,
    tags: ["vegan", "healthy", "breakfast"],
    category: "breakfast",
    ingredients: [
      { name: "pisang beku", amount: 2, unit: "buah", category: "fruits" },
      { name: "mangga beku", amount: 100, unit: "g", category: "fruits" },
      { name: "santan", amount: 100, unit: "ml", category: "dairy" },
      { name: "granola", amount: 50, unit: "g", category: "pantry" },
      { name: "kelapa parut", amount: 2, unit: "sdm", category: "pantry" },
      { name: "chia seed", amount: 1, unit: "sdm", category: "pantry" },
      { name: "madu", amount: 1, unit: "sdm", category: "pantry" },
    ],
    steps: [
      {
        step: 1,
        instruction: "Blender pisang beku, mangga beku, dan santan hingga halus dan kental.",
        time: 3,
        temperature: null,
        tips: "Jangan tambahkan terlalu banyak cairan",
      },
      {
        step: 2,
        instruction: "Tuang smoothie ke dalam mangkuk.",
        time: 1,
        temperature: null,
        tips: "Gunakan mangkuk yang sudah didinginkan",
      },
      {
        step: 3,
        instruction: "Hias dengan granola, kelapa parut, dan chia seed. Siram dengan madu.",
        time: 2,
        temperature: null,
        tips: "Susun topping dengan cantik untuk foto",
      },
    ],
    nutrition: {
      carbs: 45,
      protein: 8,
      fat: 12,
      fiber: 18,
      sugar: 25,
    },
    cost: 20000,
    prepTime: 10,
    cookTime: 0,
  },
  {
    id: 5,
    title: "Rendang Daging Sapi",
    image:
      "https://images.unsplash.com/photo-1565299585323-38174c4a6471?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "TRADISIONAL",
    time: 180,
    servings: 6,
    calories: 380,
    difficulty: "hard",
    rating: 4.9,
    reviews: 312,
    tags: ["indonesian", "spicy", "traditional"],
    category: "dinner",
    ingredients: [
      { name: "daging sapi", amount: 1, unit: "kg", category: "meat" },
      { name: "santan kental", amount: 1, unit: "liter", category: "dairy" },
      { name: "cabai merah besar", amount: 10, unit: "buah", category: "vegetables" },
      { name: "cabai keriting", amount: 15, unit: "buah", category: "vegetables" },
      { name: "bawang merah", amount: 8, unit: "siung", category: "vegetables" },
      { name: "bawang putih", amount: 6, unit: "siung", category: "vegetables" },
      { name: "jahe", amount: 3, unit: "cm", category: "spices" },
      { name: "lengkuas", amount: 4, unit: "cm", category: "spices" },
      { name: "kunyit", amount: 2, unit: "cm", category: "spices" },
      { name: "serai", amount: 3, unit: "batang", category: "herbs" },
      { name: "daun jeruk", amount: 5, unit: "lembar", category: "herbs" },
      { name: "kelapa sangrai", amount: 100, unit: "g", category: "pantry" },
    ],
    steps: [
      {
        step: 1,
        instruction: "Potong daging sapi seukuran korek api. Haluskan semua bumbu kecuali serai dan daun jeruk.",
        time: 30,
        temperature: null,
        tips: "Potong daging melawan serat agar empuk",
      },
      {
        step: 2,
        instruction: "Tumis bumbu halus hingga harum dan matang, sekitar 15 menit.",
        time: 15,
        temperature: "Medium",
        tips: "Tumis hingga bumbu tidak berbau langu",
      },
      {
        step: 3,
        instruction: "Masukkan daging, aduk rata. Masak hingga daging berubah warna.",
        time: 10,
        temperature: "Medium-high",
        tips: "Pastikan semua daging terbalut bumbu",
      },
      {
        step: 4,
        instruction: "Tuang santan, tambahkan serai dan daun jeruk. Masak dengan api kecil sambil diaduk sesekali.",
        time: 120,
        temperature: "Low",
        tips: "Sabar adalah kunci rendang yang sempurna",
      },
      {
        step: 5,
        instruction: "Lanjutkan memasak hingga santan mengering dan daging berwarna coklat kehitaman.",
        time: 60,
        temperature: "Low",
        tips: "Aduk terus agar tidak gosong",
      },
    ],
    nutrition: {
      carbs: 8,
      protein: 35,
      fat: 28,
      fiber: 3,
      sugar: 5,
    },
    cost: 85000,
    prepTime: 45,
    cookTime: 180,
  },
]

// Sample inventory data
const SAMPLE_INVENTORY = [
  { id: 1, name: "Beras", current: 2, max: 5, unit: "kg", category: "grains", expiry: "2024-03-15" },
  { id: 2, name: "Telur", current: 6, max: 12, unit: "butir", category: "dairy", expiry: "2024-02-20" },
  { id: 3, name: "Minyak Goreng", current: 1, max: 2, unit: "liter", category: "pantry", expiry: "2024-06-10" },
  { id: 4, name: "Garam", current: 0, max: 1, unit: "kg", category: "spices", expiry: "2025-01-01" },
  { id: 5, name: "Bawang Merah", current: 3, max: 5, unit: "kg", category: "vegetables", expiry: "2024-02-25" },
  { id: 6, name: "Bawang Putih", current: 2, max: 3, unit: "kg", category: "vegetables", expiry: "2024-03-01" },
]

// Categories for ingredients
const INGREDIENT_CATEGORIES = {
  vegetables: "Sayuran",
  fruits: "Buah",
  meat: "Daging",
  seafood: "Seafood",
  dairy: "Dairy & Telur",
  pantry: "Pantry",
  spices: "Bumbu",
  grains: "Grains",
  pasta: "Pasta & Noodles",
  herbs: "Herbs",
}

// Days of the week for meal planner
const DAYS_OF_WEEK = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]
const MEAL_TYPES = ["Sarapan", "Makan Siang", "Makan Malam", "Camilan"]

// Nutrition goals
const NUTRITION_GOALS = {
  calories: 2000,
  protein: 150,
  carbs: 250,
  fat: 65,
  fiber: 25,
}
